# Generated by Django 4.1.4 on 2022-12-22 21:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={"verbose_name": "Клиент", "verbose_name_plural": "Клиенты",},
        ),
        migrations.CreateModel(
            name="Videos",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name_video",
                    models.CharField(max_length=200, verbose_name="Название видео"),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True,
                        max_length=1000,
                        null=True,
                        verbose_name="Описание к видео",
                    ),
                ),
                (
                    "href",
                    models.CharField(max_length=1000, verbose_name="Ссылка_на_Видео"),
                ),
                (
                    "videofile",
                    models.FileField(null=True, upload_to="videos/", verbose_name=""),
                ),
                (
                    "userProfile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="sitemy.profile",
                        verbose_name="Клиент",
                    ),
                ),
            ],
            options={"verbose_name": "Видео", "verbose_name_plural": "Видео",},
        ),
        migrations.CreateModel(
            name="Like_DisLikes",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("likes", models.IntegerField(default=0, verbose_name="Лайки")),
                ("dislikes", models.IntegerField(default=0, verbose_name="Дизлайки")),
                (
                    "userProfile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="sitemy.profile",
                        verbose_name="Клиент",
                    ),
                ),
                (
                    "video",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="sitemy.videos"
                    ),
                ),
            ],
            options={
                "verbose_name": "Лайки и Дизлайки",
                "verbose_name_plural": "Лайки и Дизлайки",
            },
        ),
    ]
