# Generated by Django 4.1.4 on 2023-01-09 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sitemy", "0004_alter_videos_videofile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="photo",
            field=models.ImageField(blank=True, upload_to="photo", verbose_name="Фото"),
        ),
    ]
