# Generated by Django 4.1.4 on 2023-01-10 16:22

from django.db import migrations, models
import sitemy.models


class Migration(migrations.Migration):

    dependencies = [
        ("sitemy", "0006_alter_profile_photo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="photo",
            field=models.ImageField(
                default="default.jpg",
                upload_to=sitemy.models.user_directory_path,
                verbose_name="Фото",
            ),
        ),
    ]
