# Generated by Django 4.1.4 on 2023-01-10 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sitemy", "0008_alter_profile_photo"),
    ]

    operations = [
        migrations.RemoveField(model_name="videos", name="href",),
    ]
