# Generated by Django 4.1.4 on 2023-01-15 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sitemy", "0009_remove_videos_href"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="isManager",
            field=models.BooleanField(
                default=False, verbose_name="Менеджер или Пользователь"
            ),
        ),
    ]
